/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@ionic/core';
import 'ionicons';


export namespace Components {

  interface LclApp {}
  interface LclAppAttributes extends StencilHTMLAttributes {}

  interface LclButton {
    /**
    * Icon to display on the button
    */
    'iconName'?: string;
  }
  interface LclButtonAttributes extends StencilHTMLAttributes {
    /**
    * Icon to display on the button
    */
    'iconName'?: string;
  }

  interface LclCard {}
  interface LclCardAttributes extends StencilHTMLAttributes {}

  interface LclCheckbox {}
  interface LclCheckboxAttributes extends StencilHTMLAttributes {}

  interface LclChip {}
  interface LclChipAttributes extends StencilHTMLAttributes {}

  interface LclComboBox {}
  interface LclComboBoxAttributes extends StencilHTMLAttributes {}

  interface LclControlGroup {}
  interface LclControlGroupAttributes extends StencilHTMLAttributes {}

  interface LclDataTable {}
  interface LclDataTableAttributes extends StencilHTMLAttributes {}

  interface LclDateTimePicker {}
  interface LclDateTimePickerAttributes extends StencilHTMLAttributes {}

  interface LclDial {}
  interface LclDialAttributes extends StencilHTMLAttributes {}

  interface LclDialog {}
  interface LclDialogAttributes extends StencilHTMLAttributes {}

  interface LclDivider {}
  interface LclDividerAttributes extends StencilHTMLAttributes {}

  interface LclFooter {}
  interface LclFooterAttributes extends StencilHTMLAttributes {}

  interface LclFormFooter {}
  interface LclFormFooterAttributes extends StencilHTMLAttributes {}

  interface LclFormHeader {}
  interface LclFormHeaderAttributes extends StencilHTMLAttributes {}

  interface LclFormSection {}
  interface LclFormSectionAttributes extends StencilHTMLAttributes {}

  interface LclFormTabSection {}
  interface LclFormTabSectionAttributes extends StencilHTMLAttributes {}

  interface LclForm {}
  interface LclFormAttributes extends StencilHTMLAttributes {}

  interface LclGrid {}
  interface LclGridAttributes extends StencilHTMLAttributes {}

  interface LclHeader {}
  interface LclHeaderAttributes extends StencilHTMLAttributes {}

  interface LclImage {}
  interface LclImageAttributes extends StencilHTMLAttributes {}

  interface LclLabel {}
  interface LclLabelAttributes extends StencilHTMLAttributes {}

  interface LclListItem {}
  interface LclListItemAttributes extends StencilHTMLAttributes {}

  interface LclList {}
  interface LclListAttributes extends StencilHTMLAttributes {}

  interface LclMenu {}
  interface LclMenuAttributes extends StencilHTMLAttributes {}

  interface LclNavDrawer {}
  interface LclNavDrawerAttributes extends StencilHTMLAttributes {}

  interface LclPanel {}
  interface LclPanelAttributes extends StencilHTMLAttributes {}

  interface LclRadioButton {}
  interface LclRadioButtonAttributes extends StencilHTMLAttributes {}

  interface LclStepper {}
  interface LclStepperAttributes extends StencilHTMLAttributes {}

  interface LclSwitch {}
  interface LclSwitchAttributes extends StencilHTMLAttributes {}

  interface LclTabGroup {}
  interface LclTabGroupAttributes extends StencilHTMLAttributes {}

  interface LclTab {}
  interface LclTabAttributes extends StencilHTMLAttributes {}

  interface LclTextArea {}
  interface LclTextAreaAttributes extends StencilHTMLAttributes {}

  interface LclTextField {}
  interface LclTextFieldAttributes extends StencilHTMLAttributes {}

  interface LclToolbar {}
  interface LclToolbarAttributes extends StencilHTMLAttributes {}

  interface LclTooltip {}
  interface LclTooltipAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'LclApp': Components.LclApp;
    'LclButton': Components.LclButton;
    'LclCard': Components.LclCard;
    'LclCheckbox': Components.LclCheckbox;
    'LclChip': Components.LclChip;
    'LclComboBox': Components.LclComboBox;
    'LclControlGroup': Components.LclControlGroup;
    'LclDataTable': Components.LclDataTable;
    'LclDateTimePicker': Components.LclDateTimePicker;
    'LclDial': Components.LclDial;
    'LclDialog': Components.LclDialog;
    'LclDivider': Components.LclDivider;
    'LclFooter': Components.LclFooter;
    'LclFormFooter': Components.LclFormFooter;
    'LclFormHeader': Components.LclFormHeader;
    'LclFormSection': Components.LclFormSection;
    'LclFormTabSection': Components.LclFormTabSection;
    'LclForm': Components.LclForm;
    'LclGrid': Components.LclGrid;
    'LclHeader': Components.LclHeader;
    'LclImage': Components.LclImage;
    'LclLabel': Components.LclLabel;
    'LclListItem': Components.LclListItem;
    'LclList': Components.LclList;
    'LclMenu': Components.LclMenu;
    'LclNavDrawer': Components.LclNavDrawer;
    'LclPanel': Components.LclPanel;
    'LclRadioButton': Components.LclRadioButton;
    'LclStepper': Components.LclStepper;
    'LclSwitch': Components.LclSwitch;
    'LclTabGroup': Components.LclTabGroup;
    'LclTab': Components.LclTab;
    'LclTextArea': Components.LclTextArea;
    'LclTextField': Components.LclTextField;
    'LclToolbar': Components.LclToolbar;
    'LclTooltip': Components.LclTooltip;
  }

  interface StencilIntrinsicElements {
    'lcl-app': Components.LclAppAttributes;
    'lcl-button': Components.LclButtonAttributes;
    'lcl-card': Components.LclCardAttributes;
    'lcl-checkbox': Components.LclCheckboxAttributes;
    'lcl-chip': Components.LclChipAttributes;
    'lcl-combo-box': Components.LclComboBoxAttributes;
    'lcl-control-group': Components.LclControlGroupAttributes;
    'lcl-data-table': Components.LclDataTableAttributes;
    'lcl-date-time-picker': Components.LclDateTimePickerAttributes;
    'lcl-dial': Components.LclDialAttributes;
    'lcl-dialog': Components.LclDialogAttributes;
    'lcl-divider': Components.LclDividerAttributes;
    'lcl-footer': Components.LclFooterAttributes;
    'lcl-form-footer': Components.LclFormFooterAttributes;
    'lcl-form-header': Components.LclFormHeaderAttributes;
    'lcl-form-section': Components.LclFormSectionAttributes;
    'lcl-form-tab-section': Components.LclFormTabSectionAttributes;
    'lcl-form': Components.LclFormAttributes;
    'lcl-grid': Components.LclGridAttributes;
    'lcl-header': Components.LclHeaderAttributes;
    'lcl-image': Components.LclImageAttributes;
    'lcl-label': Components.LclLabelAttributes;
    'lcl-list-item': Components.LclListItemAttributes;
    'lcl-list': Components.LclListAttributes;
    'lcl-menu': Components.LclMenuAttributes;
    'lcl-nav-drawer': Components.LclNavDrawerAttributes;
    'lcl-panel': Components.LclPanelAttributes;
    'lcl-radio-button': Components.LclRadioButtonAttributes;
    'lcl-stepper': Components.LclStepperAttributes;
    'lcl-switch': Components.LclSwitchAttributes;
    'lcl-tab-group': Components.LclTabGroupAttributes;
    'lcl-tab': Components.LclTabAttributes;
    'lcl-text-area': Components.LclTextAreaAttributes;
    'lcl-text-field': Components.LclTextFieldAttributes;
    'lcl-toolbar': Components.LclToolbarAttributes;
    'lcl-tooltip': Components.LclTooltipAttributes;
  }


  interface HTMLLclAppElement extends Components.LclApp, HTMLStencilElement {}
  var HTMLLclAppElement: {
    prototype: HTMLLclAppElement;
    new (): HTMLLclAppElement;
  };

  interface HTMLLclButtonElement extends Components.LclButton, HTMLStencilElement {}
  var HTMLLclButtonElement: {
    prototype: HTMLLclButtonElement;
    new (): HTMLLclButtonElement;
  };

  interface HTMLLclCardElement extends Components.LclCard, HTMLStencilElement {}
  var HTMLLclCardElement: {
    prototype: HTMLLclCardElement;
    new (): HTMLLclCardElement;
  };

  interface HTMLLclCheckboxElement extends Components.LclCheckbox, HTMLStencilElement {}
  var HTMLLclCheckboxElement: {
    prototype: HTMLLclCheckboxElement;
    new (): HTMLLclCheckboxElement;
  };

  interface HTMLLclChipElement extends Components.LclChip, HTMLStencilElement {}
  var HTMLLclChipElement: {
    prototype: HTMLLclChipElement;
    new (): HTMLLclChipElement;
  };

  interface HTMLLclComboBoxElement extends Components.LclComboBox, HTMLStencilElement {}
  var HTMLLclComboBoxElement: {
    prototype: HTMLLclComboBoxElement;
    new (): HTMLLclComboBoxElement;
  };

  interface HTMLLclControlGroupElement extends Components.LclControlGroup, HTMLStencilElement {}
  var HTMLLclControlGroupElement: {
    prototype: HTMLLclControlGroupElement;
    new (): HTMLLclControlGroupElement;
  };

  interface HTMLLclDataTableElement extends Components.LclDataTable, HTMLStencilElement {}
  var HTMLLclDataTableElement: {
    prototype: HTMLLclDataTableElement;
    new (): HTMLLclDataTableElement;
  };

  interface HTMLLclDateTimePickerElement extends Components.LclDateTimePicker, HTMLStencilElement {}
  var HTMLLclDateTimePickerElement: {
    prototype: HTMLLclDateTimePickerElement;
    new (): HTMLLclDateTimePickerElement;
  };

  interface HTMLLclDialElement extends Components.LclDial, HTMLStencilElement {}
  var HTMLLclDialElement: {
    prototype: HTMLLclDialElement;
    new (): HTMLLclDialElement;
  };

  interface HTMLLclDialogElement extends Components.LclDialog, HTMLStencilElement {}
  var HTMLLclDialogElement: {
    prototype: HTMLLclDialogElement;
    new (): HTMLLclDialogElement;
  };

  interface HTMLLclDividerElement extends Components.LclDivider, HTMLStencilElement {}
  var HTMLLclDividerElement: {
    prototype: HTMLLclDividerElement;
    new (): HTMLLclDividerElement;
  };

  interface HTMLLclFooterElement extends Components.LclFooter, HTMLStencilElement {}
  var HTMLLclFooterElement: {
    prototype: HTMLLclFooterElement;
    new (): HTMLLclFooterElement;
  };

  interface HTMLLclFormFooterElement extends Components.LclFormFooter, HTMLStencilElement {}
  var HTMLLclFormFooterElement: {
    prototype: HTMLLclFormFooterElement;
    new (): HTMLLclFormFooterElement;
  };

  interface HTMLLclFormHeaderElement extends Components.LclFormHeader, HTMLStencilElement {}
  var HTMLLclFormHeaderElement: {
    prototype: HTMLLclFormHeaderElement;
    new (): HTMLLclFormHeaderElement;
  };

  interface HTMLLclFormSectionElement extends Components.LclFormSection, HTMLStencilElement {}
  var HTMLLclFormSectionElement: {
    prototype: HTMLLclFormSectionElement;
    new (): HTMLLclFormSectionElement;
  };

  interface HTMLLclFormTabSectionElement extends Components.LclFormTabSection, HTMLStencilElement {}
  var HTMLLclFormTabSectionElement: {
    prototype: HTMLLclFormTabSectionElement;
    new (): HTMLLclFormTabSectionElement;
  };

  interface HTMLLclFormElement extends Components.LclForm, HTMLStencilElement {}
  var HTMLLclFormElement: {
    prototype: HTMLLclFormElement;
    new (): HTMLLclFormElement;
  };

  interface HTMLLclGridElement extends Components.LclGrid, HTMLStencilElement {}
  var HTMLLclGridElement: {
    prototype: HTMLLclGridElement;
    new (): HTMLLclGridElement;
  };

  interface HTMLLclHeaderElement extends Components.LclHeader, HTMLStencilElement {}
  var HTMLLclHeaderElement: {
    prototype: HTMLLclHeaderElement;
    new (): HTMLLclHeaderElement;
  };

  interface HTMLLclImageElement extends Components.LclImage, HTMLStencilElement {}
  var HTMLLclImageElement: {
    prototype: HTMLLclImageElement;
    new (): HTMLLclImageElement;
  };

  interface HTMLLclLabelElement extends Components.LclLabel, HTMLStencilElement {}
  var HTMLLclLabelElement: {
    prototype: HTMLLclLabelElement;
    new (): HTMLLclLabelElement;
  };

  interface HTMLLclListItemElement extends Components.LclListItem, HTMLStencilElement {}
  var HTMLLclListItemElement: {
    prototype: HTMLLclListItemElement;
    new (): HTMLLclListItemElement;
  };

  interface HTMLLclListElement extends Components.LclList, HTMLStencilElement {}
  var HTMLLclListElement: {
    prototype: HTMLLclListElement;
    new (): HTMLLclListElement;
  };

  interface HTMLLclMenuElement extends Components.LclMenu, HTMLStencilElement {}
  var HTMLLclMenuElement: {
    prototype: HTMLLclMenuElement;
    new (): HTMLLclMenuElement;
  };

  interface HTMLLclNavDrawerElement extends Components.LclNavDrawer, HTMLStencilElement {}
  var HTMLLclNavDrawerElement: {
    prototype: HTMLLclNavDrawerElement;
    new (): HTMLLclNavDrawerElement;
  };

  interface HTMLLclPanelElement extends Components.LclPanel, HTMLStencilElement {}
  var HTMLLclPanelElement: {
    prototype: HTMLLclPanelElement;
    new (): HTMLLclPanelElement;
  };

  interface HTMLLclRadioButtonElement extends Components.LclRadioButton, HTMLStencilElement {}
  var HTMLLclRadioButtonElement: {
    prototype: HTMLLclRadioButtonElement;
    new (): HTMLLclRadioButtonElement;
  };

  interface HTMLLclStepperElement extends Components.LclStepper, HTMLStencilElement {}
  var HTMLLclStepperElement: {
    prototype: HTMLLclStepperElement;
    new (): HTMLLclStepperElement;
  };

  interface HTMLLclSwitchElement extends Components.LclSwitch, HTMLStencilElement {}
  var HTMLLclSwitchElement: {
    prototype: HTMLLclSwitchElement;
    new (): HTMLLclSwitchElement;
  };

  interface HTMLLclTabGroupElement extends Components.LclTabGroup, HTMLStencilElement {}
  var HTMLLclTabGroupElement: {
    prototype: HTMLLclTabGroupElement;
    new (): HTMLLclTabGroupElement;
  };

  interface HTMLLclTabElement extends Components.LclTab, HTMLStencilElement {}
  var HTMLLclTabElement: {
    prototype: HTMLLclTabElement;
    new (): HTMLLclTabElement;
  };

  interface HTMLLclTextAreaElement extends Components.LclTextArea, HTMLStencilElement {}
  var HTMLLclTextAreaElement: {
    prototype: HTMLLclTextAreaElement;
    new (): HTMLLclTextAreaElement;
  };

  interface HTMLLclTextFieldElement extends Components.LclTextField, HTMLStencilElement {}
  var HTMLLclTextFieldElement: {
    prototype: HTMLLclTextFieldElement;
    new (): HTMLLclTextFieldElement;
  };

  interface HTMLLclToolbarElement extends Components.LclToolbar, HTMLStencilElement {}
  var HTMLLclToolbarElement: {
    prototype: HTMLLclToolbarElement;
    new (): HTMLLclToolbarElement;
  };

  interface HTMLLclTooltipElement extends Components.LclTooltip, HTMLStencilElement {}
  var HTMLLclTooltipElement: {
    prototype: HTMLLclTooltipElement;
    new (): HTMLLclTooltipElement;
  };

  interface HTMLElementTagNameMap {
    'lcl-app': HTMLLclAppElement
    'lcl-button': HTMLLclButtonElement
    'lcl-card': HTMLLclCardElement
    'lcl-checkbox': HTMLLclCheckboxElement
    'lcl-chip': HTMLLclChipElement
    'lcl-combo-box': HTMLLclComboBoxElement
    'lcl-control-group': HTMLLclControlGroupElement
    'lcl-data-table': HTMLLclDataTableElement
    'lcl-date-time-picker': HTMLLclDateTimePickerElement
    'lcl-dial': HTMLLclDialElement
    'lcl-dialog': HTMLLclDialogElement
    'lcl-divider': HTMLLclDividerElement
    'lcl-footer': HTMLLclFooterElement
    'lcl-form-footer': HTMLLclFormFooterElement
    'lcl-form-header': HTMLLclFormHeaderElement
    'lcl-form-section': HTMLLclFormSectionElement
    'lcl-form-tab-section': HTMLLclFormTabSectionElement
    'lcl-form': HTMLLclFormElement
    'lcl-grid': HTMLLclGridElement
    'lcl-header': HTMLLclHeaderElement
    'lcl-image': HTMLLclImageElement
    'lcl-label': HTMLLclLabelElement
    'lcl-list-item': HTMLLclListItemElement
    'lcl-list': HTMLLclListElement
    'lcl-menu': HTMLLclMenuElement
    'lcl-nav-drawer': HTMLLclNavDrawerElement
    'lcl-panel': HTMLLclPanelElement
    'lcl-radio-button': HTMLLclRadioButtonElement
    'lcl-stepper': HTMLLclStepperElement
    'lcl-switch': HTMLLclSwitchElement
    'lcl-tab-group': HTMLLclTabGroupElement
    'lcl-tab': HTMLLclTabElement
    'lcl-text-area': HTMLLclTextAreaElement
    'lcl-text-field': HTMLLclTextFieldElement
    'lcl-toolbar': HTMLLclToolbarElement
    'lcl-tooltip': HTMLLclTooltipElement
  }

  interface ElementTagNameMap {
    'lcl-app': HTMLLclAppElement;
    'lcl-button': HTMLLclButtonElement;
    'lcl-card': HTMLLclCardElement;
    'lcl-checkbox': HTMLLclCheckboxElement;
    'lcl-chip': HTMLLclChipElement;
    'lcl-combo-box': HTMLLclComboBoxElement;
    'lcl-control-group': HTMLLclControlGroupElement;
    'lcl-data-table': HTMLLclDataTableElement;
    'lcl-date-time-picker': HTMLLclDateTimePickerElement;
    'lcl-dial': HTMLLclDialElement;
    'lcl-dialog': HTMLLclDialogElement;
    'lcl-divider': HTMLLclDividerElement;
    'lcl-footer': HTMLLclFooterElement;
    'lcl-form-footer': HTMLLclFormFooterElement;
    'lcl-form-header': HTMLLclFormHeaderElement;
    'lcl-form-section': HTMLLclFormSectionElement;
    'lcl-form-tab-section': HTMLLclFormTabSectionElement;
    'lcl-form': HTMLLclFormElement;
    'lcl-grid': HTMLLclGridElement;
    'lcl-header': HTMLLclHeaderElement;
    'lcl-image': HTMLLclImageElement;
    'lcl-label': HTMLLclLabelElement;
    'lcl-list-item': HTMLLclListItemElement;
    'lcl-list': HTMLLclListElement;
    'lcl-menu': HTMLLclMenuElement;
    'lcl-nav-drawer': HTMLLclNavDrawerElement;
    'lcl-panel': HTMLLclPanelElement;
    'lcl-radio-button': HTMLLclRadioButtonElement;
    'lcl-stepper': HTMLLclStepperElement;
    'lcl-switch': HTMLLclSwitchElement;
    'lcl-tab-group': HTMLLclTabGroupElement;
    'lcl-tab': HTMLLclTabElement;
    'lcl-text-area': HTMLLclTextAreaElement;
    'lcl-text-field': HTMLLclTextFieldElement;
    'lcl-toolbar': HTMLLclToolbarElement;
    'lcl-tooltip': HTMLLclTooltipElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
